### PR TITLE
Added Table.compare

### PR DESCRIPTION
**Pull request by DaRealFrost**
This functions main goal is to compare two tables and return if the two tables passed in are identical.

### CODE REVIEW

**Comment by DaRealFrost** [comment]
@dr4wn When you get some free time, could you merge this. Its been tested and works on my end.

**Review by DaRealFrost — COMMENTED** [review]
All good on my end.

**Review by Stoppedwumm — APPROVED** [review]
Looks good

**Comment by Stoppedwumm** [comment]
> > Looks good
> 
> Who are you? 🤣

Devxos little bro- nah jk I'm an dev who learned python with 8, js with 10, Lua with 13 and demands all inertia products to be open-sourced bc communism

**Review by dr4wn — APPROVED** [review]
looks good to me

**Pull request merged**
