### PR TITLE
Feature: Integer, Number, and more

### PR DESCRIPTION
**Pull request by DaRealFrost**
Added Function:
CreateInstance(Class, Name, RandomName)

Description:
Allows for easy creation of instances from one place.

### CODE REVIEW

**Comment by DaRealFrost** [comment]
Commit 2:

Added Functions:
isOdd(number)
isEven(number)
calculateHalf(number)
absoluteValue(number)
maximum(a, b)
minimum(a, b)
round(number)
power(base, exponent)
squareRoot(number)
sine(number)
cosine(number)
tangent(number)
randomInRange(min, max)

Description:
Makes interacting with Integers on roblox easier

**Comment by MidSpike** [comment]
I adjusted a few areas of this PR.

Most importantly, I saw that most of the added methods don't bring any additions to Lua.

However I like the idea of having the `Number` and `Integer` sub-modules.

`calculateHalf` was converted into `Integer.divide(input, divisor) -> floor, ceil` which helps facilitate code re-usability and adds additional functionality that could have been included before.

**Comment by MidSpike** [comment]
Created `LA.Lego.Instance.create`.

I'm not 100% on the naming for this one, but the method is now consistent with the rest of the library.

**Comment by DaRealFrost** [comment]
Added Color.lua

Added Functions:
rgbToHsv(red, green, blue)
rgbToHtml(red, green, blue)
hsvToRgb(hue, saturation, value)
hsvToHtml(hue, saturation, value)
htmlToRgb(htmlColorCode)
htmlToHsv(htmlColorCode)

Description:
Allows for converting colors

**Comment by MidSpike** [comment]
@WillFJS awaiting your review

**Comment by DaRealFrost** [comment]
@MidSpike This ever gonna be closed? 😂

**Review by WillFJS — APPROVED** [review]

**Review by MidSpike — APPROVED** [review]

**Pull request merged**
